#!/usr/bin/env ruby

require "bundler/setup"
require "commander/import"
require "fileutils"

root = File.expand_path('../', __dir__)

program :name, 'install'
program :version, '1.0.0'
program :description, 'neovimrc管理'

command :install do |c|
  c.syntax = 'neovimrc install'
  c.description = '安装vimrc文件'
  c.action do |args, options|
    neovim_dir = File.join(Dir.home, '.config/nvim')
    unless File.directory?(neovim_dir)
      log 'create', "neovim dir ($XDG_CONFIG_HOME) => ~/.config"
      FileUtils.mkdir_p neovim_dir

      log 'install', 'vim-plug'
      %x{curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim}
      # %x{git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim}

      log 'create', 'vimrc'
      FileUtils.cp File.join(root, 'resources/vimrc'), File.join(neovim_dir, 'init.vim')

      log 'create', 'vim undo dir'
      FileUtils.mkdir_p File.join(neovim_dir, 'undo')

      log 'create', 'vim backup dir'
      FileUtils.mkdir_p File.join(neovim_dir, 'backup')

      log 'create', 'vim swp dir'
      FileUtils.mkdir_p File.join(neovim_dir, 'swp')

      log 'install', 'python support'
      %x{sudo pip install neovim --upgrade}

      # log 'install', 'install vim plugin'
      # %x{nvim +PlugInstall}

    end
  end
end


command :clear do |c|
  c.syntax = 'neovimrc clear'
  c.description = '清除neovimrc配置'
  c.action do |args, options|
    log 'remove', '~/.nvimrc'
    FileUtils.rm_rf File.join(Dir.home, '.nvimrc')

    log 'remove', '~/.vim'
    FileUtils.rm_rf File.join(Dir.home, '.vim')
  end
end

command :update do |c|
  c.syntax = 'neovimrc update'
  c.description = '更新vimrc文件'
  c.action do |args, options|
    neovim_dir = File.join(Dir.home, '.config/nvim')
    log 'update', 'vimrc'
    FileUtils.cp File.join(root, 'resources/vimrc'), File.join(neovim_dir, 'init.vim')

    log 'install', 'python support'
    %x{sudo pip install neovim --upgrade}

    log 'run', 'nvim +PlugUpgrade'
    %x{nvim +PlugUpgrade}

    # log 'run', 'nvim +PlugUpdate'
    # %x{nvim +PlugUpdate}
  end
end

